# Generated by Django 4.1.7 on 2023-04-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Birthday', 'hbd'), ('Anniversary', 'anv'), ('Valentine', 'vlt'), ('Flowers', 'flw'), ('Chocolate', 'clt'), ('Plants', 'pla'), ('Electronic', 'elt'), ('Jewels', 'jwl')], max_length=20)),
            ],
        ),
    ]
