# Generated by Django 4.2 on 2023-04-20 09:01

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to=product.models.upload_path),
        ),
    ]
